# Generated by Django 4.2.7 on 2023-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Total_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery_person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rentee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='id',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='Rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='delivery_person',
            name='Serial_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rentee',
            name='NID',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='renter',
            name='SSN',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='renter',
            name='Rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
