# Generated by Django 4.2.7 on 2023-12-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_clothingitem_renter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='User_ID',
            new_name='renter_id',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
