# Generated by Django 4.2.7 on 2023-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_remove_cart_total_amount_remove_cart_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_person',
            name='Serial_ID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
