# Generated by Django 4.2.7 on 2023-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0003_alter_delivery_person_serial_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_person',
            old_name='Serial_ID',
            new_name='SSN',
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
