# Generated by Django 4.2.7 on 2023-12-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0004_rename_serial_id_delivery_person_ssn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='Rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='Reviews',
            field=models.ManyToManyField(blank=True, related_name='clothing_items', to='Cloth.review'),
        ),
    ]
